apiVersion: v1
kind: Pod
metadata: 
  name: pod-cm-2
  namespace: default
  labels: 
    app: myapp
    tier: frontend
  annotations:
    magedu.com/created-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: nginxconf
      mountPath: /etc/nginx/config.d/   #挂载点不存在则自动创建
      readOnly: true
  volumes:
  - name: nginxconf
    configMap:
      name: my-config
#使用kubectl edit cm cm名   修改之后里面的机器文件也会相应的改变
