apiVersion: v1
kind: Pod
metadata: 
  name: pod-cm-1
  namespace: default
  labels: 
    app: myapp
    tier: frontend
  annotations:
    magedu.com/created-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80
    env:
    - name: NGINX_SERVER_PORT      #使用下划线，大写表示环境变量
      valueFrom:
        configMapKeyRef:
          name: nginx              #这里的name表示configmap的名字
          key: nginx_port
    - name: NGINX_SERVER_NAME
      valueFrom:
        configMapKeyRef:
          name: nginx               #如上
          key: server_name
          
       
